# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS    ?= /opt/blocksds/core

NAME        := bwt

SOURCEDIRS  := source

INCLUDEDIRS := include \
              ../libndspp/include \
              ../3rdparty/zlib-1.3.1/ \
              ../3rdparty/zlib-1.3.1/contrib/minizip/ \

GFXDIRS     := img

WARNFLAGS_CPP := -Wall -Wno-deprecated-declarations

include ../make/lib_template.make
