# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS    ?= /opt/blocksds/core

NAME        := bunjalloo

SOURCEDIRS  := source
INCLUDEDIRS := include \
               ../3rdparty/mbedtls-3.6.4/include/ \
               ../libbwt/include/ \
               ../libndspp/include/ \

WARNFLAGS_CPP := -Wall -Wno-deprecated-declarations

include ../make/lib_template.make
